### PR TITLE
Fix type hints for older versions of python (<3.9)

### PR DESCRIPTION
**Pull request by jakeberesford-palmetto**
## Pull request checklist

Before submitting your PR, please review the following checklist:

- [x] Consider adding a unit test if your PR resolves an issue.
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Breaking changes

- [ ] Check if this pull request introduces a breaking change

## What does this implement/fix? Explain your changes.

Older versions of Python will raise an error when typehints do not use the imported Type class from typing.

## Does this close any currently open issues?
#30

## Where has this been tested?

**Operating System:**Mac OS

### CODE REVIEW

**Comment by jakeberesford-palmetto** [comment]
@emekdahl-palmetto - can you checkout my branch, install the plugin from source, and test to confirm it resolved the bug you reported in #30

**Review by ethanknox-palmetto — APPROVED** [review]
so technically you _can_ pass the actual primitive as the type if you want (ie `tuple` instead of `Tuple`) but the typing class is more versatile and probably better practice. for example you can't do `tuple[str, str]` it has to be `Tuple[str,str]`. 

What bothers me is that `tuple[str,str]` never should have compiled anywhere. That should have exploded immediately. WTF typing. why you no say thing

**Comment by jakeberesford-palmetto** [comment]
> so technically you _can_ pass the actual primitive as the type if you want (ie `tuple` instead of `Tuple`) but the typing class is more versatile and probably better practice. for example you can't do `tuple[str, str]` it has to be `Tuple[str,str]`.
> 
> What bothers me is that `tuple[str,str]` never should have compiled anywhere. That should have exploded immediately. WTF typing. why you no say thing

Yeah, I'm surprised that this wasn't caught earlier. We need to figure out how to set up our tests to run against multiple python versions in CI

**Review by emekdahl-palmetto — APPROVED** [review]

**Comment by ethanknox-palmetto** [comment]
> > so technically you _can_ pass the actual primitive as the type if you want (ie `tuple` instead of `Tuple`) but the typing class is more versatile and probably better practice. for example you can't do `tuple[str, str]` it has to be `Tuple[str,str]`.
> > What bothers me is that `tuple[str,str]` never should have compiled anywhere. That should have exploded immediately. WTF typing. why you no say thing
> 
> Yeah, I'm surprised that this wasn't caught earlier. We need to figure out how to set up our tests to run against multiple python versions in CI

we could do it in docker and mount the socket but that's a nightmare in CI because GH really, really doesn't want you touching their docker daemon. the common pattern there is to do docker-ception, which we could do if we want 

The other option is to use make since we are building in throw-away CI envs. which is not a bad deal in that case. install each supported version of python using deadsnakes, then loop through and make a venv, activate, run tests, deactivate etc for each version. This would at least give us a single OS run in each python env which is fine to start

**Comment by jakeberesford-palmetto** [comment]
> 

I think it can be more simple than that... something like this in a GH action should work

```
    strategy:
      matrix:
        python-version:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
    container: python:${{ python-version }}
```

**Pull request merged**
